import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "../stack/client";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quicksandBold = localFont({
  src: "./fonts/Quicksand-Bold.ttf",
  variable: "--font-quicksand-bold",
});

const quicksandRegular = localFont({
  src: "./fonts/Quicksand-Regular.ttf",
  variable: "--font-quicksand-regular",
});

const quicksandLight = localFont({
  src: "./fonts/Quicksand-Light.ttf",
  variable: "--font-quicksand-light",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${quicksandBold.variable} ${quicksandRegular.variable} ${quicksandLight.variable} antialiased`}><StackProvider app={stackClientApp}><StackTheme>
        {children}
      </StackTheme>

      </StackProvider>
      </body>
    </html>
  );
}
